export const ERROR_CODES = {
  // General errors
  NOT_FOUND: "NOT_FOUND",


  // User errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  
  // Auth errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  MISSING_AUTH_HEADER: "MISSING_AUTH_HEADER",
  
  // GitHub errors
  GITHUB_USER_NOT_FOUND: "GITHUB_USER_NOT_FOUND",
  GITHUB_API_ERROR: "GITHUB_API_ERROR",
  GITHUB_NO_REPOSITORIES: "GITHUB_NO_REPOSITORIES",
  GITHUB_SERVICE_ERROR: "GITHUB_SERVICE_ERROR",
  GITHUB_API_RATE_LIMIT_EXCEEDED: "GITHUB_API_RATE_LIMIT_EXCEEDED",

  // Project errors
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_REPOSITORY_ERROR: "PROJECT_REPOSITORY_ERROR",
  
  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MISSING_PARAMETER: "MISSING_PARAMETER",
  INVALID_PARAMETER: "INVALID_PARAMETER",
  
  // System errors
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE"
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];